name: run integration testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: localUser
          POSTGRES_PASSWORD: localPassword
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.0

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        which migrate

    #- name: Install postgres client
    #  run: sudo apt-get install -y postgresql-client

    - name: Make paths
      run: mkdir bin

    - name: Verify dependencies
      run: go mod verify

    #- name: create db
    #  run: |
    #    export DB_PASS=localPassword && export DB_USER=localUser && export DB_NAME=test && export DB_HOST=localhost && export DB_PORT=5432 && make create_db

    - name: Make migration
      run: |
        export DB_PASS=localPassword && export DB_USER=localUser && export DB_NAME=test && export DB_HOST=localhost && export DB_PORT=5432 && make migrate_up

    - name: Build service
      run: go build -o bin/adv_task ./cmd

    - name: Run tests
      run: export DB_PASS=localPassword && export DB_USER=localUser && export DB_NAME=test && export DB_HOST=localhost && export DB_PORT=5432 && go test -v ./...

    - name: Rollback migration
      run: |
        export DB_PASS=localPassword && export DB_USER=localUser && export DB_NAME=test && export DB_HOST=localhost && export DB_PORT=5432 && make migrate_down

    #- name: drop db
    #  run: |
    #    export DB_PASS=localPassword && export DB_USER=localUser && export DB_NAME=test && export DB_HOST=localhost && export DB_PORT=5432 && make drop_db
